README.md
docs/_markbind/layouts/default.md
docs/index.md
docs/site.json

* Update url of our tp page in default.md
* Changed codecov url in index.md
* Update site.json

Fix bug on failed pages deployment

---

docs/AboutUs.md

* The Java CI workflow have a start up failure previously as no permission was given to run it.
* The action permissions for our tp repo is changed to accommodate workflow runs. 
* This branch is created to stimulate the rerun of Java CI workflows for the upstream master branch.

Enable rerun of workflows 

---

docs/AboutUs.md
docs/UserGuide.md

User Guide Feature & Command Updated with 2 new sections: 
- A Guide to reading each command
- How to interpret a command format

Update User Guide

---

README.md
docs/UserGuide.md

Change Quick Start section in UG

Update UG 

---

docs/UserGuide.md

Add the UI mockup and link it via a relative path.

Add mockup to User Guide

---

docs/DeveloperGuide.md

Add NFRs to Developer Guide

---

README.md
docs/UserGuide.md

Elaborate about delete, search, favourites and exit commands

Edit user guide

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/team/frrrrry.md

Done by adding a few more commits and pushing a new branch to see test if the java ci checks still fails.

Attempt to fix workflow run failure

---

src/main/java/seedu/address/logic/commands/FavouriteCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java

* Create FavouriteCommand and FavouriteCommandParser
* Update related model classes 
Resolve #61

Add Favourite Command

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCourseCommand.java
src/main/java/seedu/address/logic/commands/FindRoleCommand.java
src/main/java/seedu/address/logic/commands/FindTutorialCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FindCourseCommandParser.java
src/main/java/seedu/address/logic/parser/FindRoleCommandParser.java
src/main/java/seedu/address/logic/parser/FindTutorialCommandParser.java
src/main/java/seedu/address/model/person/Course.java
src/main/java/seedu/address/model/person/CourseContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/Role.java
src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/TutorialContainsKeywordsPredicate.java

Add the following features:
* Search by name
* Search by role
* Search by tutorial
* Search by course
* Exit

Add Search and Exit Commands

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Tutorial.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java

Previously, there was no simple way to find the course that matches a specific Tutorial when trying to create a Tutorial object.
This is a common scenario, so the classes had to manually search through a set of Courses to find a Course that would be pointed at by the Tutorial. This is very annoying, highly inefficient, and requires much code repetition.
Let's add a new method to Tutorial that would take a set of Courses, search through it, and then return the relevant Course. This would result in much less repetitive code.

Add a method for Tutorial to find its course

---

src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Tutorial.java
src/test/java/seedu/address/logic/commands/ExitCommandTest.java
src/test/java/seedu/address/logic/commands/FindCourseCommandTest.java
src/test/java/seedu/address/logic/commands/FindRoleCommandTest.java
src/test/java/seedu/address/logic/commands/FindTutorialCommandTest.java

Add testcases for:
* search
* searchrole
* searchcourse
* searchtutorial
* exit

Add search testcases

---

src/main/java/seedu/address/MainApp.java

Previously, a bug existed where clicking the X button on the application, instead of entering the exit command, does not save the data in the app.
Let's fix that by making the data save when the app is exited.

Fixed bug where data is not saved when user exits the app.

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Contact.java
src/main/java/seedu/address/model/person/Course.java
src/main/java/seedu/address/model/person/Tutorial.java
src/main/java/seedu/address/storage/JsonAdaptedCourse.java
src/main/java/seedu/address/ui/PersonCard.java

Previously there were bugs in: 
1. the saving of tutorials, where the added tutorials were not saved under the tutorial list
2. the tutorials were also saved under the course list
3. when multiple contacts were being added, they are being saved as one contact instead of separate contacts. 
4. Third point also happens to when multiple courses were being added

Fix bugs related to tutorials, courses and contacts

---

src/main/java/seedu/address/model/person/Tutorial.java
src/test/java/seedu/address/model/person/RoleTest.java
src/test/java/seedu/address/model/person/TutorialTest.java

Add test cases for both role and tutorial classes

Add role, tutorial testcases

---

build.gradle
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/UniquePersonListTest.java
src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Update configurations: 
* Enable assertions in build.gradle
Testing: 
* Rewrite json test files to be used for JsonAdaptedXXXTest 
* Uncomment out test cases
* Fix bug detected by test case in which ParseException is not thrown when parsing invalid contacts and courses
* Update EditCommandTest to do the basic of editting names only (we will implement editing other fields soon)

Add testcases

---

src/main/java/seedu/address/logic/commands/UnfavouriteCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/UnfavouriteCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Favourite.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/UnfavouriteCommandParserTest.java

* Similar to favourite feature, unfavourite simply unfavourites a Person present in the person list through specifying the index of the Person in the person list. 
* Added testcases for unfavourite feature. 
Resolves #103

Add Unfavourite feature

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/PersonListCard.fxml

Added a tag for each of the role
I commented out the label for roles first because I think that having both the tag and the label are a bit messy
Can still add it in after that if needed

Add Role Tag

---

src/test/java/seedu/address/logic/commands/FindRoleCommandTest.java
src/test/java/seedu/address/model/person/CourseContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/RoleContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/TutorialContainsKeywordsPredicateTest.java

Add Testcases for:
1. CourseContainsKeywordsPredicate
2. RoleContainsKeywordsPredicate
3. TutorialContainsKeywordsPredicate
4. NameContainsKeywordsPredicate

Add Person testcases

---

src/main/java/seedu/address/logic/parser/FindCourseCommandParser.java
src/main/java/seedu/address/logic/parser/FindRoleCommandParser.java
src/main/java/seedu/address/logic/parser/FindTutorialCommandParser.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindCourseCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindRoleCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindTutorialCommandParserTest.java
src/test/java/seedu/address/logic/parser/UnfavouriteCommandParserTest.java

Add Parser testcases for:
* FindCourseCommandParser
* FindRoleCommandParser
* FindCourseCommandParser
* FindCommandParser
Edit other parser test files to include additional test cases that cover various input scenarios.

Add Parser testcases

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java

The declaration of parsecommand was inside of the switch command, let's fixed it so it is outside of switch command, ensuring a return statement for parseCommand method.

fix problems related to merge conflicts

---

docs/UserGuide.md

* Change heading levels of the UG
* Change design of section separator
* Move help to first feature
* Move fav and unfav before favlist

Update format of the UG

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Adding more fields after clear and help command does not return an error. Let's make sure that it returns an error.

Fix help and clear command'd feedback error

---

docs/UserGuide.md
docs/team/frrrrry.md
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/FavListCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/test/java/seedu/address/logic/commands/FavListCommandTest.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java

* Change "profiles" to "person" in output messages to ensure that it is consistent with the UG
* Fix favlist bug where the persons listed have their contacts double-bracketed which is inconsistent with what is in the UG
* Update fry's ppp

Change output messages 

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java

Since the edit feature has a feature flaw, we are unable to fix it due to feature freeze for v1.4. Hence, we choose to delete the edit feature.

Delete edit feature

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/FindCourseCommandParser.java
src/main/java/seedu/address/logic/parser/FindRoleCommandParser.java
src/main/java/seedu/address/logic/parser/FindTutorialCommandParser.java
src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindCourseCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindRoleCommandParserTest.java
src/test/java/seedu/address/logic/parser/FindTutorialCommandParserTest.java

* fix search validation bugs for all search commands
* update testcases for search commands

Fix search validation bug

---

docs/UserGuide.md

Update the UG after reverting the changes

Update UG with the updated add command

---

docs/DeveloperGuide.md

Add diagrams to DG for search and favlist commands

Edit feature description

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/HelpCommand.java

Update help command to include missing commands

---

docs/UserGuide.md

Resolves #264.
Resolves #267.
Resolves #269.
Resolves #270.

Fix ug bugs

---

docs/team/frrrrry.md

Update fry's ppp

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddCommand.java

Add command usage message was in the incorrect format that will cause confusion for the users. It was updated with the correct format
Fix some bugs in the UG

Fix bugs in UG and Add Command usage message
